version: "3"
services:
  app:
    image: djangoenv:1.0
    build: ./app
    container_name: "dev"
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "127.0.0.1:8000:8000"
    tty: true
  db:
    image: postgres:latest
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=app
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # - ./db:/docker-entrypoint-initdb.d
networks:
    BFnetwork:
        external: true


# docker-compose exec db psql --username=dev --dbname=app                                           ✘ 1
